"""( [('add_column', , 'users', Column('password', String(length=50), table=_users_, comment='Password'))]_,)

Revision ID: 06534dff989b
Revises: 
Create Date: 2023-05-21 15:35:01.665896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06534dff989b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irails_users', sa.Column('password', sa.String(length=50), nullable=True, comment='Password'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irails_users', 'password')
    # ### end Alembic commands ###
