"""(_New upgrade operations detected_ [('add_column', None, 'irails_users', Column('password', String(length=50), table=_irails_users_, comment='Password'))]_,)

Revision ID: 0c20459aba85
Revises: 
Create Date: 2023-05-20 22:16:15.058069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c20459aba85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irails_users', sa.Column('password', sa.String(length=50), nullable=True, comment='Password'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irails_users', 'password')
    # ### end Alembic commands ###
