"""( [('add_column', , 'users', Column('remark', String(length=255), table=_users_, comment='description'))]_,)

Revision ID: 1a4fee9f37e2
Revises: 3245265b9e30
Create Date: 2023-05-21 16:30:56.963927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4fee9f37e2'
down_revision = '3245265b9e30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irails_users', sa.Column('remark', sa.String(length=255), nullable=True, comment='description'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irails_users', 'remark')
    # ### end Alembic commands ###
