"""( [('remove_table', Table('roles', MetaData(), Column('id', INTEGER(), table=_roles_, primary_key=True, nullable=False), Column('name', VARCHAR(length=50), table=_roles_, nullable=False), Column('update_at', DATETIME(), table=_roles_, server_default=DefaultClause(_sqlalchemy.sql.elements.TextClause object at 0x00000208D8DAF460_, for_update=False)), Column('create_at', DATETIME(), table=_roles_, server_default=DefaultClause(_sqlalchemy.sql.elements.TextClause object at 0x00000208D8DAF580_, for_update=False)), schema=)), ('remove_table', Table('users', MetaData(), Column('id', INTEGER(), table=_users_, primary_key=True, nullable=False), Column('name', VARCHAR(length=50), table=_users_, nullable=False), Column('fullname', VARCHAR(length=50), table=_users_, nullable=False), Column('age', INTEGER(), table=_users_, nullable=False), Column('update_at', DATETIME(), table=_users_, server_default=DefaultClause(_sqlalchemy.sql.elements.TextClause object at 0x00000208D8DAF070_, for_update=False)), Column('create_at', DATETIME(), table=_users_, server_default=DefaultClause(_sqlalchemy.sql.elements.TextClause object at 0x00000208D8DAE4A0_, for_update=False)), Column('password', VARCHAR(length=50), table=_users_), schema=)), ('remove_table', Table('user_role', MetaData(), Column('user_id', INTEGER(), ForeignKey('users.id'), table=_user_role_, primary_key=True, nullable=False), Column('role_id', INTEGER(), ForeignKey('roles.id'), table=_user_role_, primary_key=True, nullable=False), schema=))]_,)

Revision ID: 3245265b9e30
Revises: 06534dff989b
Create Date: 2023-05-21 16:16:57.410329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3245265b9e30'
down_revision = '06534dff989b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irails_roles')
    op.drop_table('irails_users')
    op.drop_table('irails_user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irails_user_role',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['irails_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['irails_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('irails_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('password', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irails_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('update_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
