"""( [('remove_table', Table('casbin_rule', MetaData(), Column('id', INTEGER(), table=_casbin_rule_, primary_key=True, nullable=False), Column('ptype', VARCHAR(length=255), table=_casbin_rule_), Column('v0', VARCHAR(length=255), table=_casbin_rule_), Column('v1', VARCHAR(length=255), table=_casbin_rule_), Column('v2', VARCHAR(length=255), table=_casbin_rule_), Column('v3', VARCHAR(length=255), table=_casbin_rule_), Column('v4', VARCHAR(length=255), table=_casbin_rule_), Column('v5', VARCHAR(length=255), table=_casbin_rule_), schema=))]_,)

Revision ID: 9e22c9d0a599
Revises: c877717229af
Create Date: 2023-05-27 16:38:54.558268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e22c9d0a599'
down_revision = 'c877717229af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
