"""( [('add_column', , 'roles', Column('i18n_json_data', Text(), table=_roles_, server_default=DefaultClause('{}', for_update=False))), ('add_column', , 'users', Column('i18n_json_data', Text(), table=_users_, server_default=DefaultClause('{}', for_update=False)))]_,)

Revision ID: b3584a942fe0
Revises: 1a4fee9f37e2
Create Date: 2023-05-21 20:24:51.633794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3584a942fe0'
down_revision = '1a4fee9f37e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irails_roles', sa.Column('i18n_json_data', sa.Text(), server_default='{}', nullable=True))
    op.add_column('irails_users', sa.Column('i18n_json_data', sa.Text(), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irails_users', 'i18n_json_data')
    op.drop_column('irails_roles', 'i18n_json_data')
    # ### end Alembic commands ###
