"""( [('add_column', , 'users', Column('domain', String(length=50), table=_users_, nullable=False, comment='user domain'))]_,)

Revision ID: c877717229af
Revises: 
Create Date: 2023-05-27 16:18:55.755532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c877717229af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irails_users', sa.Column('domain', sa.String(length=50), nullable=True, comment='user domain'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irails_users', 'domain')
    # ### end Alembic commands ###
