"""( [('add_column', , 'products', Column('name', String(length=50), table=_products_, nullable=False, comment='name of product'))]_,)

Revision ID: cac62890c4af
Revises: af475bbdd363
Create Date: 2023-06-28 18:03:08.880871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac62890c4af'
down_revision = 'af475bbdd363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irails_products', sa.Column('name', sa.String(length=50), nullable=False, comment='name of product'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('irails_products', 'name')
    # ### end Alembic commands ###
