auth:
  adapter_table: casbin_rule
  adapter_uri: '{database.uri}'
  auth_model: configs/casbin_templates/RBACT.conf
  casbin_adapter: sqlalchemy
  secret_key: '123456'
  session_name: user
  super_domain: system
  super_group: admin
  type: jwt
