auth:
  adapter_uri: '{database.uri}' # keep empty if adpter is sqlalchemy to user database.uri same
  auth_model: configs/casbin_templates/RBACT.conf
 
  adapter_table: 'casbin_rule' 
  casbin_adapter: sqlalchemy
  secret_key: '123456'
  session_name: user
  type: jwt