database:
  alembic_ini: configs/alembic.ini
  dbdecode: gbk
  dbencode: latin-1
  dbfirst: false
  dbhost: localhost
  dbname: data/db/irails_admin.db
  dbpassword: '123456'
  dbuser: sa
  maptables: []
  table_prefix: irails_
  uri: sqlite:///{dbname}
