database:
  dbhost: 'localhost'
  dbname: 'data/db/Admin.NET.db'
  dbuser: 'sa'
  dbpassword: '123456'
  dbencode: 'latin-1'
  dbdecode: 'gbk'
  # MySQL
  # mysql+pymysql://username:password@host:port/database_name 
  # PostgreSQL
  # postgresql+psycopg2://username:password@host:port/database_name 
  # SQLite
  # sqlite:///absolute/path/to/db/file.db 3times of '/'
  # Mssql
  # mssql+pymssql://username:password@hostname:port/database_name 
  uri:    #empty to disable database connection
  # uri: 'mongodb+srv://dbbruce:smjk123@atlascluster.siz4vrp.mongodb.net/?retryWrites=true&w=majority'
  # uri: 'mssql+pymssql://{dbuser}:{dbpassword}@{dbhost}/{dbname}'
  alembic_ini: 'configs/alembic.ini' #empty or none will disable auto migrate
  dbfirst: false
  maptables: [] #['item','ba_cls_info']
