app:
  appdir:
  - apps
  enabled: null
  root: apps.root
auth:
  adapter_uri: './configs/casbin-adapter.csv'
  auth_model: ./configs/casbin-model.conf
  basic_key: '123456'
  casbin_adapter: file
  jwt_key: '123456'
  session_name: user
  type: jwt
cors:
  allow_credentials: true
  allow_headers:
  - '*'
  allow_methods:
  - '*'
  allow_origins:
  - '*'
debug: true
error_404_page: '{public_dir}/error_404.html'
error_500_page: '{public_dir}/error_500.html'
log:
  file: ''
  level: DEBUG
  name: iRails
public_dir: ./public
upload:
  dir: ./uploads
  extensions:
  - ppt
  - txt
  - xls
  - xlsx
  - docx
  - doc
  - pdf
  - png
  - jpg
  - jpeg
  - gif
  - bmp
  - svg
  - mp3
  - wav
  - ogg
  - flac
  - aac
  - mp4
  - avi
  - mkv
  - wmv
  - mov
  max: 1024*1024*10
view:
  jinja2:
    block_end_string: '%}'
    block_start_string: '{%'
    comment_end_string: '#}'
    comment_start_string: '{#'
    variable_end_string: '}'
    variable_start_string: ${
  static_format:
  - vue
  - html
i18n:
  lang: ['zh']
  url_lang_key: 'lang'