app:
  appdir:
  - apps
  enabled:
 
auth:
  adapter_uri: ./configs/casbin-adapter.csv
  auth_model: ./configs/casbin-model.conf
  basic_key: '123456'
  casbin_adapter: file
  jwt_key: '123456'
  session_name: user
  type: jwt
cors:
  allow_credentials: true
  allow_headers:
  - '*'
  allow_methods:
  - '*'
  allow_origins:
  - '*'
debug: true
error_404_page: '{public_dir}/error_404.html'
error_500_page: '{public_dir}/error_500.html'
log:
  file: ''
  level: DEBUG
  name: Test
public_dir: ./public
upload:
  dir: ./uploads
  extensions:
  - ppt
  - txt
  - xls
  - xlsx
  - docx
  - doc
  - pdf
  - png
  - jpg
  - jpeg
  - gif
  - bmp
  - svg
  - mp3
  - wav
  - ogg
  - flac
  - aac
  - mp4
  - avi
  - mkv
  - wmv
  - mov
  max: 1024*1024*10
